
-- Preview first 20 records from the dataset
SELECT * FROM customer LIMIT 20;


-- Total revenue generated by each gender group
SELECT "Gender", SUM("Purchase Amount (USD)") AS revenue
FROM customer
GROUP BY "Gender";


-- Customers who used discount and spent >= average purchase amount
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes'
AND "Purchase Amount (USD)" >= (
    SELECT AVG("Purchase Amount (USD)") FROM customer
);


-- Top 5 highest-rated products based on average review rating
SELECT "Item Purchased",
ROUND(AVG("Review Rating"::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;


-- Average purchase amount for Standard vs Express shipping
SELECT "Shipping Type",
ROUND(AVG("Purchase Amount (USD)"),2) AS avg_purchase
FROM customer
WHERE "Shipping Type" IN ('Standard','Express')
GROUP BY "Shipping Type";


-- Subscription-based analysis: total customers, avg spend, total revenue
SELECT "Subscription Status",
COUNT("Customer ID") AS total_customers,
ROUND(AVG("Purchase Amount (USD)"),2) AS avg_spend,
ROUND(SUM("Purchase Amount (USD)"),2) AS total_revenue
FROM customer
GROUP BY "Subscription Status"
ORDER BY total_revenue DESC, avg_spend DESC;


-- Top 5 products with highest discount usage rate (%)
SELECT "Item Purchased",
ROUND(
100.0 * SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2
) AS discount_rate
FROM customer
GROUP BY "Item Purchased"
ORDER BY discount_rate DESC
LIMIT 5;


-- Customer segmentation based on previous purchases
WITH customer_type AS (
    SELECT "Customer ID", "Previous Purchases",
    CASE 
        WHEN "Previous Purchases" = 1 THEN 'New'
        WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
    FROM customer
)

-- Count customers in each segment
SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


-- Top 3 most ordered items in each category
WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY "Category"
               ORDER BY COUNT("Customer ID") DESC
           ) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)

SELECT item_rank, "Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Repeat buyers (>5 purchases) grouped by subscription status
SELECT "Subscription Status",
COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";


-- Revenue contribution by age group (highest to lowest)
SELECT "Age",
SUM("Purchase Amount (USD)") AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue DESC;